export default {
  EXPORT_FILE_PATH: 'public/export/',
  TIMEZONE: `Asia/Taipei`,

  DATE_FORMAT_DASH_YYYY_MM_DD: `YYYY-MM-DD`,
  DATE_FORMAT_DASH_MMM_YYYY: `MMM-YYYY`,
  DATE_FORMAT_BOTTOM_DASH_YYYY_MM_DD_HH_MM_SS: `YYYY_MM_DD_HH_mm_ss`,
  DATE_FORMAT_YYYYMMDDHHMMSS: `YYYYMMDDHHmmss`,
  DATE_FORMAT_BOTTOM_STANDARD_YYYY_MM_DD_HH_MM_SS: `YYYY-MM-DD HH:mm:ss`,
  DATE_FORMAT_BOTTOM_DASH_YYYY_MM: `YYYY_MM`,
  DATE_FORMAT_SLASH_YYYY_MM_DD: `YYYY/MM/DD`,
  DATE_FORMAT_YYYY: `YYYY`,
  DATE_FORMAT_YYYYMM: `YYYYMM`,
  DATE_FORMAT_YYYYMMDD: `YYYYMMDD`,
  DATE_FORMAT_MMDD: `MMDD`,

  HISTORY_TYPE_EVENT: `event`,
  HISTORY_TYPE_COMMENT: `comment`,

  EVENT_TYPE_ADD: `add`,
  EVENT_TYPE_UPDATE: `update`,
  EVENT_TYPE_WORKFLOW: `workflow`,
  EVENT_TYPE_NOTIFY: `notify`,
  EVENT_TYPE_APPROVE: `approve`,
  EVENT_TYPE_DELETE: `delete`,
  EVENT_TYPE_REJECT: `reject`,
  EVENT_TYPE_COMMENT_FOR_APPROVE: `comment for approve`,
  EVENT_TYPE_COMMENT_FOR_REJECT: `comment for reject`,

  DATA_EXTRACT_FILE_PATH: './public/template/data extract.xlsx',

  XLSX_COL_TYPE_TEXT: `text`,
  XLSX_COL_TYPE_NUMBER: `number`,
  XLSX_COL_TYPE_PERCENT: `percent`,
  XLSX_COL_TYPE_TIMESTAMP: `timestamp`,

};
