version: '3.5'

services:
  app:
    container_name: nestjs-test
    image: nestjs-test:latest
    build:
      dockerfile: docker/Dockerfile
      context: ../
    ports:
      - '3000:3000'
    tty: true
