FROM node:16-alpine

RUN apk update && apk add tzdata
ENV TZ=Asia/Hong_Kong

RUN apk --no-cache add git
WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .

ENV NODE_ENV=development

EXPOSE 3000

CMD ["npm", "run", "start:dev"]